# Generated by Django 5.1 on 2026-06-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_location', models.CharField(blank=True, max_length=256, null=True)),
                ('new_location', models.CharField(blank=True, max_length=256, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(help_text='Unikalny identyfikator, np. TOOL-0042 lub numer z kodu kreskowego', max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('responsible_unit', models.CharField(blank=True, help_text='Sekcja lub osoba odpowiedzialna za przedmiot', max_length=128, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('exact_location', models.CharField(blank=True, help_text='Opcjonalne dokładne miejsce, np. szafka_A3, półka_2', max_length=256, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
