# Generated by Django 5.1 on 2026-06-24 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='home_location',
            field=models.ForeignKey(blank=True, help_text='Domyślna lokalizacja do której przedmiot powinien wracać', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_items', to='items.location'),
        ),
    ]
